MainProject/Controllers/FavoritesController.cs
using AutoMapper;
using Core.Dtos;
using Core.Services;
using Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MainProject.Extensions;
using MainProject.Services;

namespace MainProject.Controllers
{
    public class FavoritesController : Controller
    {
        private readonly IFavoriteService favoriteService;

        public FavoritesController(IFavoriteService favoriteService)
        {
            this.favoriteService = favoriteService;
        }
        // відображає сторінку корзини із доданими продуктами
        public IActionResult Index()
        {
            return View(favoriteService.GetProducts());
        }

        // додає продукт в корзину
        public IActionResult Add(int id, string? returnUrl)
        {
            favoriteService.Add(id);
            return Redirect(returnUrl ?? "/");
        }

        // видаляє продукт з корзини
        public IActionResult Remove(int id)
        {
            favoriteService.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

MainProject/Controllers/HomeController.cs
using Data;
using MainProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace MainProject.Controllers
{
    public class HomeController : Controller
    {

        private readonly MoviesDbContext context;

        public HomeController(MoviesDbContext context)
        {
            this.context = context;
        }
       

        public IActionResult Index()
        {
            var movies = context.Movie
               .Include(x => x.FilmGenres) // LEFT JOIN
               .ToList();

            return View(movies); 
        }

        public IActionResult Privacy()
        {
            return View();
        }

       
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MainProject/Views/Home/About.cshtml
<h1>About Page!</h1>

<p>This is super puper page...</p>

<button type="button" class="btn btn-primary">Do Nothing!</button>

<div class="mt-3">
    @for (int i = 0; i < 5; i++)
    {
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    }
</div>

MainProject/Views/Home/Index.cshtml
@model List<Movie>
@using Data.Entities;

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>
        Learn about <a href="https://learn.microsoft.com/aspnet/core">
            building Web apps with ASP.NET Core
        </a>.
    </p>

    @if (DateTime.Now.Minute % 2 == 0)
    {
        <p>Current minute is <span class="badge bg-info text-dark">even!</span></p>
    }
    else
    {
        <p>Current minute is <span class="badge bg-warning text-dark">odd!</span></p>
    }
</div>


<div class="row row-cols-4 g-3">
    @foreach (var i in Model)
    {
        <div class="col">
            <div class="card text-center" style="width: 18rem;">
                <img height="170" src="@i.ImageUrl" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">
                        <a asp-controller="Products" asp-action="Details" asp-route-id="@i.Id">
                            @i.Name
                        </a>
                    </h5>
                    <p class="card-text">@i.Lenght - @i.Rating</p>
                    <a asp-controller="Favorites" asp-action="Add" asp-route-id="@i.Id" asp-route-returnUrl="@Context.Request.Path" class="btn btn-primary">Add to Favorites</a>
                </div>
            </div>
        </div>
    }
</div>